import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";
import type { PagesFunction } from "@remix-run/cloudflare-pages";

import { onRequestGet as contactGet, onRequestPost as contactPost } from "./api/contact";

// The build output is generated by `remix vite:build`
// and includes the server runtime at `build/server/index.js`.
// Cloudflare Pages Functions will bundle this import at deploy time.
// eslint-disable-next-line import/no-unresolved
// @ts-ignore - generated at build time
import * as build from "../build/server/index.js";

const remixHandler = createPagesFunctionHandler({
  build,
});

export const onRequest: PagesFunction = async (ctx) => {
  const url = new URL(ctx.request.url);

  // Ensure /api/contact works even when the Remix catch-all function is used as the entrypoint.
  if (url.pathname === "/api/contact") {
    if (ctx.request.method === "POST") return contactPost(ctx as any);
    if (ctx.request.method === "GET") return contactGet(ctx as any);
    return new Response("Method not allowed", { status: 405 });
  }

  return remixHandler(ctx);
};


