import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// The build output is generated by `remix vite:build`
// and includes the server runtime at `build/server/index.js`.
// Cloudflare Pages Functions will bundle this import at deploy time.
// eslint-disable-next-line import/no-unresolved
// @ts-ignore - generated at build time
import * as build from "../build/server/index.js";

export const onRequest = createPagesFunctionHandler({
  build,
});


